### PR TITLE
SECURE_PROCESSING_FEATURE

### PR DESCRIPTION
**Pull request by ronsigal**
Added the features and properties for secure processing. 

See attached secure-configuration-guide.pdf.

### CODE REVIEW

**Comment by ronsigal** [comment]
secure-configuration-guide.pdf: 
  https://github.com/jboss/xerces/files/72334/secure-configuration-guide.pdf

**Comment by wolfc** [comment]
The commits prior to a438a94 should not be there. a438a94 in itself should not be there as well.
Rather d3271bd should be rebased on top of jboss:jboss-2.11.0.SP in a topic branch and a PR should be filed from that topic branch.

**Comment by ronsigal** [comment]
Ok, Carlo, I'll change it.

**Comment by ronsigal** [comment]
This Pull Request is replaced by https://github.com/jboss/xerces/pull/12.

**Pull request closed without merging**
